input_type: "mesh"
output_type: "occ" # or sdf or occ
augment: False
mlps_folder_train: ./mlp_weights/ginr_simplified_overfit_relu/
mlps_type: ginr
filter_bad: False
in_out: True
augment_on_the_fly: False
mesh_jitter: False
jitter_augment: False
dataset_dir: ./data/sdf/171shape_occ_sdf/
dataset: "obj"
normalize_input: True
wandb_dir: .
batch_size: 2048
lr: 1e-2
model_type: mlp_3d
bayesian: False
logging_root: './logs'
shape_modify: 'no'
exp_name: "save_pc"
steps_til_summary: 100
epochs_til_ckpt: 1
hidden_features: 128
kl_weight: 0
epochs: 5000
scheduler:
  type: adaptive
  step_size: 30
  gamma: 0.1
  min_lr: 1e-5
  patience: 50
  patience_adaptive: 10
  factor: 0.8
  threshold: 0
multi_process:
  enabled: False
  part_id: 0
  n_of_parts: 4
  first_weights_name:
  ignore_first: False
n_points: 100000
is_meta: True
strategy: first_weights
clip_grad: False

mlp_config:
  params:
    model_type: mlp_3d
    out_size: 1
    hidden_neurons:
      - 128
      - 128
      - 128
    output_type: occ
    out_act: sigmoid
    multires: 4
    use_leaky_relu: False
    move: False

arch:
  type: meta_low_rank_modulated_inr
  ema: null
  n_inner_step: 4
  inner_lr: 0.0003
  hyponet:
    type: mlp
    n_layer: 6
    hidden_dim:
    - 256
    use_bias: true
    share_bias: false
    input_dim: 3
    output_dim: 2
    output_bias: 0.0
    fourier_mapping:
      type: PE
      trainable: false
      use_ff: true
      ff_sigma: 4
      ff_dim: 27
    activation:
      type: relu
      siren_w0: null
    initialization:
      weight_init_type: kaiming_uniform
      bias_init_type: zero
    normalize_weight: true
  rank:
  - 128
  modulated_layer_idxs:
  - 1
  use_factorization: false
  coord_sampler:
    data_type: image
    coord_range:
    - -1.0
    - 1.0
    train_strategy: null
    val_strategy: null
experiment_name: overfit_ginr_simplified
save_folder : ./results.tmp/ply
